-- 문제: 12세 이하인 여자 환자 목록 출력하기
-- 분류: SELECT
-- 날짜: 2026-07-12

SELECT 
PT_NAME, 
PT_NO, 
GEND_CD, 
AGE, 
IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC